import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Footer} from "../components/footer"
import Links from '../components/links'
import Headline from '../components/Headline'

export function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline 
          page="about"
        />
        <Links />
      </main>
      
      <Footer />
    </div>
  )
}
